// <auto-generated />
namespace TaskTracerApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class WorkGroupCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkGroupCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201410242219558_WorkGroupCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
